### ISSUE TITLE
Would you like to Merge this repo?

### ISSUE THREAD

**Issue by sberlow** [dberlow/AmstelvarNew#1]
with https://github.com/TypeNetwork/Amstelvar
This would prent the saving of data related to the same project in tow different places.

If the goal is to work outside the current font until you want to merge, I would suggest a fork in the main repo. This way all of the data will remain in one repo and can be merged as you approve.

**Comment by dberlow** [comment]
DJR and I are working on it. Right now they represent a separation between work on the Roman in the italic, they will be merged by Monday thanks.

**Comment by sberlow** [comment]
Great
